name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          mkdir dist
          pandoc --pdf-engine=tectonic --template template.tex -o dist/en.pdf README.md
          pandoc --pdf-engine=tectonic --template template.tex -o dist/it.pdf README_IT.md
          pandoc -o dist/en.html README.md
          pandoc -o dist/it.html README_IT.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
