name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1

      - run: tlmgr install inter fontawesome5
      - run: mkdir dist
      - run: pandoc --pdf-engine=xelatex -o dist/cv.pdf HEADING.md README.md
      - run: pandoc -o dist/index.html README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
